os_name: ~
file_system: ~
docker_mode: root
services_restart_policy: always

projects:
  - name: dashboard
    src: git@github.com:resoul/football.manager.dashboard.git
  - name: api
    src: git@github.com:resoul/football.manager.api.git

enabled_services:
  - db
  - api
  - dashboard
  - adminer

