os_name: ~
file_system: ~
docker_mode: root
services_restart_policy: always

projects:
  - name: fm-dashboard
    src: git@github.com:resoul/football.manager.dashboard.git
  - name: fm-api
    src: git@github.com:resoul/football.manager.api.git

enabled_services:
  - fm-db
  - fm-api
  - fm-dashboard
  - fm-mailhog
  - fm-adminer

